services:
  e621tagger:
    container_name: e621tagger
    image: ghcr.io/fenrir784/e621tagger:latest
    restart: unless-stopped
    pull_policy: always
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: 12
    expose:
      - 5000
    networks:
      - lushway_web
    environment:
      - TZ=Europe/Moscow
      - SAVE_UPLOADS=true
      - USE_PROXY=true
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=120
    volumes:
      - /home/fenrir784/e621tagger-saved/uploads:/app/uploads
    labels:
      - traefik.enable=true
      - traefik.http.routers.tagger.rule=Host(`www.tagger.fenrir784.ru`)
      - traefik.http.routers.tagger.entrypoints=websecure
networks:
  lushway_web:
    external: true
