services:
  e621tagger:
    build: .
    ports:
      - "5000:5000"
    environment:
      - THRESHOLD=0.55
      - SAVE_UPLOADS=true
      - UPLOAD_DIR=/app/uploads
      # - DEVICE=cuda
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped