            - name: Delete Package Versions
  uses: actions/delete-package-versions@v5.0.0
  with:
    # Comma separated string of package version ids to delete.
    package-version-ids: # optional
    # Owner of the repo containing the package version to delete. Defaults to the owner of the repo running the action.

    owner: # optional
    # Name of the package containing the version to delete.

    package-name: e621tagger
    # Type of package. Can be one of container, maven, npm, nuget, or rubygems.

    package-type: container
    # Number of versions to delete starting with the oldest version. Defaults to 1.

    num-old-versions-to-delete: 1000 # optional, default is 1
    # Number of versions to keep starting with the latest version By default keeps no version. To delete all versions set this as 0.

    min-versions-to-keep: 10 # optional, default is -1
    # Regex pattern for package versions to ignore. Defaults to delete all versions.

    ignore-versions: # optional, default is ^$
    # Deletes only pre-release versions. The number of pre-release versions to keep can be specified by min-versions-to-keep. When this is set num-old-versions-to-delete and ignore-versions will not be taken into account. By default this is set to false

    delete-only-pre-release-versions: # optional, default is false
    # Deletes only untagged versions in case of a container package. Does not work for other package types. The number of untagged versions to keep can be specified by min-versions-to-keep. When this is set num-old-versions-to-delete will not be taken into account. By default this is set to false

    delete-only-untagged-versions: # optional, default is false
    # Token with the necessary scopes to delete package versions. If num-old-versions-to-delete is used the token also needs the read packages scope. Defaults to github.token scoped to the repo running the action. To delete package versions of a package outside the repo the action is running in use a Personal Access Token stored as a secret.

    token: # optional, default is ${{ github.token }}
          
